(define (count-changes amount-in-dollar)
  (define (coin-value-by-cents kind)
    (cond ((= kind 1) 1)
          ((= kind 2) 5)
          ((= kind 3) 10)
          ((= kind 4) 25)
          ((= kind 5) 50)
          ((= kind 6) 100)
          ((= kind 7) 500)
          ((= kind 8) 1000)
          ((= kind 9) 2000)
          ((= kind 10) 5000)
          ((= kind 11) 10000)
          ))
  (define (count-changes-with-kind amount-in-cents kind-of-coins)
  (cond ((= amount-in-cents 0) 1)
        ((< amount-in-cents 0) 0)
        ((= kind-of-coins 0) 0)
        (else (+ (count-changes-with-kind amount-in-cents (- kind-of-coins 1)) 
           (count-changes-with-kind (- amount-in-cents 
                                      (coin-value-by-cents kind-of-coins)) 
                                      kind-of-coins)))))
  (count-changes-with-kind (* amount-in-dollar 100) 11))

(count-changes 0)
(count-changes 0.01)
(count-changes 0.05)
(count-changes 1)
(count-changes 5)