(define (good-enough? guess last-guess)
  (< (abs (- guess last-guess)) (* 0.000000001 last-guess) ))
(define (improve guess x) 
  (average guess (/ x guess)))
(define (average x y) 
  (/ (+ x y) 2.0))
(define (sqrt-iter guess last-guess x) 
  (if (good-enough? guess last-guess) 
      guess 
      (sqrt-iter (improve guess x) 
                 guess x)))
(define (sqrt x) (sqrt-iter 1.0 x x))
(sqrt 2)
(sqrt 1e308)
(sqrt 1e-308)