(define (square x) (* x x))
(define (good-enough? guess last-guess)
  (< (abs (- guess last-guess)) (* 0.000000001 last-guess) ))
(define (improve guess x)
  (/ (+ (* 2 guess) (/ x (square guess))) 3.0))
(define (cbrt-iter guess last-guess x)
  (if (good-enough? guess last-guess)
      guess
      (cbrt-iter (improve guess x)
                 guess x)))
(define (cbrt x) 
  (if (>= x 0)
      (cbrt-iter 1.0 x x)
      (- (cbrt-iter 1.0 (abs x) (abs x)))))

(cbrt 1)
(cbrt 8)
(cbrt 1e303)
(cbrt 1e-303)
(cbrt -1)
(cbrt -1e303)